# Generated by Django 5.1.4 on 2025-02-23 11:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ma_KH', models.CharField(editable=False, max_length=10, unique=True)),
                ('Ten_KH', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ma_MH', models.CharField(max_length=10)),
                ('Ten_MH', models.CharField(max_length=100)),
                ('Don_Gia', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='NH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ma_NH', models.CharField(max_length=10)),
                ('Ten_NH', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PKKH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ma_PKKH', models.CharField(max_length=3)),
                ('Mo_Ta', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('Thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('Ma_Kh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ass.kh')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Line_id', models.CharField(max_length=10)),
                ('SL', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ass.bill')),
                ('Ma_MH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ass.mh')),
            ],
        ),
        migrations.AddField(
            model_name='mh',
            name='Ma_NH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ass.nh'),
        ),
        migrations.AddField(
            model_name='kh',
            name='Ma_PKKH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ass.pkkh'),
        ),
    ]
