# Generated by Django 5.1.4 on 2025-02-24 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ass', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='Ma_Kh',
            new_name='Ma_KH',
        ),
        migrations.AlterField(
            model_name='bill_line',
            name='Bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_lines', to='django_ass.bill'),
        ),
    ]
