# Generated by Django 5.1.4 on 2025-02-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ass', '0002_rename_ma_kh_bill_ma_kh_alter_bill_line_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mh',
            name='Ma_MH',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nh',
            name='Ma_NH',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pkkh',
            name='Ma_PKKH',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
