# Generated by Django 5.1.4 on 2025-02-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ass', '0003_alter_mh_ma_mh_alter_nh_ma_nh_alter_pkkh_ma_pkkh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Bill_id',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='kh',
            name='Ten_KH',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mh',
            name='Ten_MH',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nh',
            name='Ten_NH',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
