# Generated by Django 5.1.4 on 2025-02-27 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ass', '0004_alter_bill_bill_id_alter_kh_ten_kh_alter_mh_ten_mh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Bill_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Thoi_gian',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='kh',
            name='Ma_KH',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
